name: Notify Slack Channel on Pull Request Updates

on:
  workflow_call:
    secrets:
      SLACK_API_TOKEN:
        required: true
  pull_request:
    types:
      - opened
      - closed
      - approved
      - rejected

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install
      - name: Send Slack notification
        env:
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
          PULL_REQUEST_ID: ${{ github.event.pull_request.id }}
          PULL_REQUEST_TITLE: ${{ github.event.pull_request.title }}
          PULL_REQUEST_URL: ${{ github.event.pull_request.html_url }}
          PULL_REQUEST_AUTHOR: ${{ github.event.pull_request.user.login }}
          PULL_REQUEST_STATE: ${{ github.event.pull_request.state }}
        run: |
          echo "Sending Slack notification..."
          node .github/workflows/notify.js
