name: Notify Slack Channel on Pull Request Updates

on:
  pull_request:
    types:
      - opened
      - closed
      - approved
      - rejected

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install
      - name: Send Slack notification
        run: |
          echo "Sending Slack notification..."
          node notify.js
